/**
 * CRITICAL CROSS-LANGUAGE TEST
 *
 * Loads Python-generated receipt fixtures from spec/fixtures/receipts/
 * and verifies them with the TypeScript verifier. This proves that
 * receipts generated by the Python reference implementation can be
 * verified by the TypeScript SDK — the core promise of cross-language
 * receipt portability.
 *
 * Note: v1.0 fixtures use 12-field fingerprint. v1.1 uses 14-field.
 * Fingerprint recomputation tests are skipped for v1.0 fixtures;
 * signature, content hash, and golden value tests still apply.
 */

import { describe, it, expect } from "vitest";
import { resolve } from "node:path";
import { readFileSync, readdirSync } from "node:fs";
import { verifyReceipt } from "../src/verifier.js";
import { computeFingerprints } from "../src/receipt.js";
import { loadPublicKey } from "../src/crypto.js";
import { hashObj, EMPTY_HASH } from "../src/hashing.js";

const FIXTURES = resolve(__dirname, "../../../spec/fixtures");
const golden = JSON.parse(
  readFileSync(resolve(FIXTURES, "golden-hashes.json"), "utf-8"),
);
const pubKey = loadPublicKey(resolve(FIXTURES, "keypairs/test-author.pub"));

// Load all receipt fixtures
const receiptDir = resolve(FIXTURES, "receipts");
const receiptFiles = readdirSync(receiptDir).filter((f) => f.endsWith(".json"));
const receipts: Record<string, Record<string, unknown>> = {};
for (const file of receiptFiles) {
  const name = file.replace(".json", "");
  receipts[name] = JSON.parse(readFileSync(resolve(receiptDir, file), "utf-8"));
}

/** v1.0 fixtures use 12-field fingerprint; v1.1 uses 14-field */
function isV1Fixture(receipt: Record<string, unknown>): boolean {
  return receipt.spec_version === "1.0" || receipt.checks_version === "5";
}

// ── Cross-language verification ──────────────────────────────────────

describe("CRITICAL: cross-language receipt verification", () => {
  for (const [name, receipt] of Object.entries(receipts)) {
    describe(`receipt: ${name}`, () => {
      if (isV1Fixture(receipt)) {
        it("signature verifies (Python-signed, TypeScript-verified)", () => {
          // v1.0 fixtures: fingerprint recomputation will differ (14 vs 12 fields)
          // but signature is over the full receipt JSON, so it still verifies.
          const result = verifyReceipt(receipt, pubKey);
          expect(result.checks_performed).toContain("signature");
          expect(
            result.errors.filter((e) => e.toLowerCase().includes("signature")),
          ).toEqual([]);
        });

        it("content hashes match (Python-computed, TypeScript-recomputed)", () => {
          const computedCtx = hashObj(receipt.inputs);
          const computedOut = hashObj(receipt.outputs);
          expect(computedCtx).toBe(receipt.context_hash);
          expect(computedOut).toBe(receipt.output_hash);
        });

        it("fingerprint recomputation skipped for v1.0 fixture (12→14 field transition)", () => {
          // Document that v1.0 fixtures have 12-field fingerprints
          expect(receipt.checks_version).toBe("5");
        });
      } else {
        it("passes full verification with TypeScript verifier", () => {
          const result = verifyReceipt(receipt, pubKey);
          if (!result.valid) {
            console.error(`VERIFICATION FAILED for ${name}:`, result.errors);
          }
          expect(result.valid).toBe(true);
          expect(result.errors).toEqual([]);
        });

        it("signature verifies (Python-signed, TypeScript-verified)", () => {
          const result = verifyReceipt(receipt, pubKey);
          expect(result.checks_performed).toContain("signature");
          expect(
            result.errors.filter((e) => e.toLowerCase().includes("signature")),
          ).toEqual([]);
        });

        it("fingerprint matches (Python-computed, TypeScript-recomputed)", () => {
          const { receipt_fingerprint, full_fingerprint } =
            computeFingerprints(receipt);
          expect(receipt_fingerprint).toBe(receipt.receipt_fingerprint);
          expect(full_fingerprint).toBe(receipt.full_fingerprint);
        });

        it("content hashes match (Python-computed, TypeScript-recomputed)", () => {
          const computedCtx = hashObj(receipt.inputs);
          const computedOut = hashObj(receipt.outputs);
          expect(computedCtx).toBe(receipt.context_hash);
          expect(computedOut).toBe(receipt.output_hash);
        });
      }
    });
  }
});

// ── 14-field fingerprint unit tests ──────────────────────────────────

describe("14-field fingerprint", () => {
  it("null parent_receipts and workflow_id produce EMPTY_HASH fields", () => {
    const receipt = {
      correlation_id: "test-001",
      context_hash: "a".repeat(64),
      output_hash: "b".repeat(64),
      checks_version: "6",
      checks: [],
      parent_receipts: null,
      workflow_id: null,
    };
    const fp1 = computeFingerprints(receipt);

    // Same as without those fields entirely
    const receipt2 = {
      correlation_id: "test-001",
      context_hash: "a".repeat(64),
      output_hash: "b".repeat(64),
      checks_version: "6",
      checks: [],
    };
    const fp2 = computeFingerprints(receipt2);
    expect(fp1.full_fingerprint).toBe(fp2.full_fingerprint);
  });

  it("non-null parent_receipts changes fingerprint", () => {
    const base = {
      correlation_id: "test-001",
      context_hash: "a".repeat(64),
      output_hash: "b".repeat(64),
      checks_version: "6",
      checks: [],
    };
    const fp1 = computeFingerprints(base);
    const fp2 = computeFingerprints({
      ...base,
      parent_receipts: ["abc123"],
    });
    expect(fp1.full_fingerprint).not.toBe(fp2.full_fingerprint);
  });

  it("non-null workflow_id changes fingerprint", () => {
    const base = {
      correlation_id: "test-001",
      context_hash: "a".repeat(64),
      output_hash: "b".repeat(64),
      checks_version: "6",
      checks: [],
    };
    const fp1 = computeFingerprints(base);
    const fp2 = computeFingerprints({
      ...base,
      workflow_id: "wf-001",
    });
    expect(fp1.full_fingerprint).not.toBe(fp2.full_fingerprint);
  });

  it("content_mode does NOT change fingerprint", () => {
    const base = {
      correlation_id: "test-001",
      context_hash: "a".repeat(64),
      output_hash: "b".repeat(64),
      checks_version: "6",
      checks: [],
    };
    const fp1 = computeFingerprints(base);
    const fp2 = computeFingerprints({
      ...base,
      content_mode: "redacted",
      content_mode_source: "local_config",
    });
    expect(fp1.full_fingerprint).toBe(fp2.full_fingerprint);
  });

  it("different parent_receipts arrays produce different fingerprints", () => {
    const base = {
      correlation_id: "test-001",
      context_hash: "a".repeat(64),
      output_hash: "b".repeat(64),
      checks_version: "6",
      checks: [],
    };
    const fp1 = computeFingerprints({
      ...base,
      parent_receipts: ["abc"],
    });
    const fp2 = computeFingerprints({
      ...base,
      parent_receipts: ["def"],
    });
    expect(fp1.full_fingerprint).not.toBe(fp2.full_fingerprint);
  });

  it("deterministic: same inputs produce same fingerprint", () => {
    const receipt = {
      correlation_id: "det-001",
      context_hash: "c".repeat(64),
      output_hash: "d".repeat(64),
      checks_version: "6",
      checks: [],
      parent_receipts: ["parent-fp-1"],
      workflow_id: "wf-det-001",
    };
    const fp1 = computeFingerprints(receipt);
    const fp2 = computeFingerprints(receipt);
    expect(fp1.receipt_fingerprint).toBe(fp2.receipt_fingerprint);
    expect(fp1.full_fingerprint).toBe(fp2.full_fingerprint);
  });
});

// ── Golden hash values ───────────────────────────────────────────────

describe("CRITICAL: golden hash cross-verification", () => {
  for (const [name, goldenData] of Object.entries(
    golden.receipts as Record<string, Record<string, unknown>>,
  )) {
    const receipt = receipts[name];
    if (!receipt) continue;

    describe(`golden: ${name}`, () => {
      it("receipt_fingerprint matches golden", () => {
        expect(receipt.receipt_fingerprint).toBe(goldenData.receipt_fingerprint);
      });

      it("full_fingerprint matches golden", () => {
        expect(receipt.full_fingerprint).toBe(goldenData.full_fingerprint);
      });

      it("context_hash matches golden", () => {
        expect(receipt.context_hash).toBe(goldenData.context_hash);
      });

      it("output_hash matches golden", () => {
        expect(receipt.output_hash).toBe(goldenData.output_hash);
      });

      it("signature key_id matches golden", () => {
        const sig = receipt.receipt_signature as Record<string, unknown>;
        expect(sig.key_id).toBe(goldenData.signature_key_id);
      });

      it("status matches golden", () => {
        expect(receipt.status).toBe(goldenData.status);
      });

      it("checks_passed matches golden", () => {
        expect(receipt.checks_passed).toBe(goldenData.checks_passed);
      });

      it("checks_failed matches golden", () => {
        expect(receipt.checks_failed).toBe(goldenData.checks_failed);
      });
    });
  }
});
