/**
 * CRITICAL CROSS-LANGUAGE TEST
 *
 * Loads Python-generated receipt fixtures from spec/fixtures/receipts/
 * and verifies them with the TypeScript verifier. This proves that
 * receipts generated by the Python reference implementation can be
 * verified by the TypeScript SDK — the core promise of cross-language
 * receipt portability.
 */

import { describe, it, expect } from "vitest";
import { resolve } from "node:path";
import { readFileSync, readdirSync } from "node:fs";
import { verifyReceipt } from "../src/verifier.js";
import { computeFingerprints } from "../src/receipt.js";
import { loadPublicKey } from "../src/crypto.js";
import { hashObj } from "../src/hashing.js";

const FIXTURES = resolve(__dirname, "../../../spec/fixtures");
const golden = JSON.parse(
  readFileSync(resolve(FIXTURES, "golden-hashes.json"), "utf-8"),
);
const pubKey = loadPublicKey(resolve(FIXTURES, "keypairs/test-author.pub"));

// Load all receipt fixtures
const receiptDir = resolve(FIXTURES, "receipts");
const receiptFiles = readdirSync(receiptDir).filter((f) => f.endsWith(".json"));
const receipts: Record<string, Record<string, unknown>> = {};
for (const file of receiptFiles) {
  const name = file.replace(".json", "");
  receipts[name] = JSON.parse(readFileSync(resolve(receiptDir, file), "utf-8"));
}

// ── Cross-language verification ──────────────────────────────────────

describe("CRITICAL: cross-language receipt verification", () => {
  for (const [name, receipt] of Object.entries(receipts)) {
    describe(`receipt: ${name}`, () => {
      it("passes full verification with TypeScript verifier", () => {
        const result = verifyReceipt(receipt, pubKey);
        if (!result.valid) {
          // Print detailed errors for debugging
          console.error(`VERIFICATION FAILED for ${name}:`, result.errors);
        }
        expect(result.valid).toBe(true);
        expect(result.errors).toEqual([]);
      });

      it("signature verifies (Python-signed, TypeScript-verified)", () => {
        const result = verifyReceipt(receipt, pubKey);
        expect(result.checks_performed).toContain("signature");
        expect(
          result.errors.filter((e) => e.toLowerCase().includes("signature")),
        ).toEqual([]);
      });

      it("fingerprint matches (Python-computed, TypeScript-recomputed)", () => {
        const { receipt_fingerprint, full_fingerprint } =
          computeFingerprints(receipt);
        expect(receipt_fingerprint).toBe(receipt.receipt_fingerprint);
        expect(full_fingerprint).toBe(receipt.full_fingerprint);
      });

      it("content hashes match (Python-computed, TypeScript-recomputed)", () => {
        const computedCtx = hashObj(receipt.inputs);
        const computedOut = hashObj(receipt.outputs);
        expect(computedCtx).toBe(receipt.context_hash);
        expect(computedOut).toBe(receipt.output_hash);
      });
    });
  }
});

// ── Golden hash values ───────────────────────────────────────────────

describe("CRITICAL: golden hash cross-verification", () => {
  for (const [name, goldenData] of Object.entries(
    golden.receipts as Record<string, Record<string, unknown>>,
  )) {
    const receipt = receipts[name];
    if (!receipt) continue;

    describe(`golden: ${name}`, () => {
      it("receipt_fingerprint matches golden", () => {
        expect(receipt.receipt_fingerprint).toBe(goldenData.receipt_fingerprint);
      });

      it("full_fingerprint matches golden", () => {
        expect(receipt.full_fingerprint).toBe(goldenData.full_fingerprint);
      });

      it("context_hash matches golden", () => {
        expect(receipt.context_hash).toBe(goldenData.context_hash);
      });

      it("output_hash matches golden", () => {
        expect(receipt.output_hash).toBe(goldenData.output_hash);
      });

      it("signature key_id matches golden", () => {
        const sig = receipt.receipt_signature as Record<string, unknown>;
        expect(sig.key_id).toBe(goldenData.signature_key_id);
      });

      it("status matches golden", () => {
        expect(receipt.status).toBe(goldenData.status);
      });

      it("checks_passed matches golden", () => {
        expect(receipt.checks_passed).toBe(goldenData.checks_passed);
      });

      it("checks_failed matches golden", () => {
        expect(receipt.checks_failed).toBe(goldenData.checks_failed);
      });
    });
  }
});
